version: "3.8"

services:
  devdb:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: dechat_db
      POSTGRES_USER: dechat_db
      POSTGRES_DB: dechat_db
    volumes:
      - ./devdb:/var/lib/postgresql/data
